collections:
  categorys:
    output: true

defaults:
  - scope:
      path: ""
      type: "categorys"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"